### ISSUE TITLE
problem with units of wavelength property

### ISSUE THREAD

**Issue by simontorres** [astropy/specutils#214]
I'm trying to use `Spectrum1D` in a small project I'm experimenting on and I'm trying to access the property `wavelength`.

```python

import matplotlib.pyplot as plt
from specutils import Spectrum1D

sample_file = 'file.fits'

spec1d = Spectrum1D.read(sample_file, format='wcs1d-fits')

plt.plot(spec1d.wavelength, spec1d.flux)
plt.show()
```

And I get the following error, here is the full traceback.

```terminal
INFO:root:Spectrum file looks like wcs1d-fits
Spectrum1D
WARNING: FITSFixedWarning: 'datfix' made the change 'Changed '2004-07-30        ' to '2004-07-30T00:00:00.0''. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: 'datfix' made the change 'Changed '2004-07-30        ' to '2004-07-30T00:00:00.0''.
Traceback (most recent call last):
  File "/data/simon/development/soar/spectrum-matcher/spectrum_matcher/match.py", line 51, in <module>
    match_spectrum()
  File "/data/simon/development/soar/spectrum-matcher/spectrum_matcher/match.py", line 20, in __call__
    self.gui()
  File "/data/simon/development/soar/spectrum-matcher/spectrum_matcher/gui/gui.py", line 103, in __call__
    self.__plot_reference()
  File "/data/simon/development/soar/spectrum-matcher/spectrum_matcher/gui/gui.py", line 182, in __plot_reference
    self.ref_plot, = self.ax_data.plot(self.ref_ccd.wavelength,
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/specutils/spectra/spectrum1d.py", line 125, in wavelength
    return self.spectral_axis.to(u.AA, u.spectral())
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/units/quantity.py", line 844, in to
    return self._new_view(self._to_value(unit, equivalencies), unit)
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/units/quantity.py", line 816, in _to_value
    equivalencies=equivalencies)
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/units/core.py", line 977, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/units/core.py", line 911, in _get_converter
    raise exc
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/units/core.py", line 897, in _get_converter
    self, other, self._normalize_equivalencies(equivalencies))
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/units/core.py", line 881, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: '' (dimensionless) and 'Angstrom' (length) are not convertible


```

If I do the same using `spec1d.spectral_axis` the plot shows just right in angstrom values but I guess is a unitless quantity.

I remember discussing about this before but could not find an issue about this.

**Comment by nmearl** [comment]
This error means that the `wcs1d-fits` loader was unable to find a spectral axis unit, and so assumed the spectral axis is unitless. The `wavelength` method attempts to explicitly convert the given spectral axis into a physical type of length (e.g. in the case that your spectral axis is loaded in frequency space, for instance). But since the spectral axis is defined to be unitless, it fails.

I would suggest either providing your own loader, or making sure that `file.fits` has the spectral axis unit in the place that the `wcs1d-fits` is expecting.

**Comment by crawfordsm** [comment]
Another option that would be sensible to add though would be to allow the user to specify the units in the reader as this information is not always in the header.  If it isn't in the header, it also might be useful to give a warning while loading the file.

**Comment by simontorres** [comment]
I'm sorry for commenting a closed issue. We should expand the meaning of "Users" in this context> I think there are "developer-users" and "non-developer-users". If the goal of specutils is to serve developers then that approach is correct. But if the goal are non-developer users, which I more inclined to believe, @crawfordsm suggestion is a good approach.

**Comment by nmearl** [comment]
Sorry, perhaps I should clarify a bit: the approach @crawfordsm mentions _alread_ exists in specutils (re: settings units in the reader) -- the only part that does not currently implemented is a warning being raised if parsing the fits could not find unit information in the header. I do agree that this should exist in the default readers, but since this functionality is just astropy's fits reader, a deeper check on the header values should exist in the astropy fits machinery if that's desired.

But perhaps this conversation should occur in a new issue.
