### ISSUE TITLE
world_to_pixel does not allow units on input

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#288]
I tried passing a Quantity to world_to_pixel:
```
In [6]: spectrum.wcs.world_to_pixel([0.58*u.um])
```
but it returns an error:
```
TypeError: only dimensionless scalar quantities can be converted to Python scalars
```
It is based on this line:
https://github.com/astropy/specutils/blob/master/specutils/wcs/adapters/gwcs_adapter.py#L38

I am not sure if I am misunderstanding how this should work or if this is a bug.

This is indirectly related to https://github.com/astropy/specutils/issues/287#issuecomment-415267924 as well.

It should be easy to fix and I can create a PR, just want to confirm that this isn't something by design.

@eteq @crawfordsm @nmearl

**Comment by nmearl** [comment]
Hmm,

```python
In [11]: from specutils import Spectrum1D; import numpy as np; import astropy.units as u

In [12]: spec = Spectrum1D(spectral_axis=np.arange(20, 71) * u.Hz,
    ...:                       flux=np.random.sample((10, 50)))
    ...:
WARNING:root:GWCS does not store rest frequency information. Please define the rest value explicitly in the `Spectrum1D` object.
WARNING:root:GWCS does not store rest wavelength information. Please define the rest value explicitly in the `Spectrum1D` object.

In [13]: spec.wcs.world_to_pixel([31.7] * u.Hz)
Out[13]: array([11.7])
```

Seems to work for me. Can you try the above code?

**Comment by brechmos-stsci** [comment]
If I do `spec.wcs.world_to_pixel([31.7] * u.Hz)` I get the error:
```
UnitsError: Can only apply 'less' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
```

If I do `spec.wcs.world_to_pixel([31.7 * u.Hz])` I get the error:
```
UnitsError: Can only apply 'less' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
```

I believe I up-to-date on master (top of my git log):
```
commit fd608603541a6bf1d5a8bb153bd1beaba1646a85 (HEAD -> master, specutils/master, origin/master, origin/HEAD)
Merge: 6585bbc 989c58c
Author: Erik Tollerud <erik.tollerud@gmail.com>
Date:   Tue Aug 21 14:46:44 2018 -0400

    Merge pull request #284 from drdavella/add-test

    Add unit test for multidimensional flux
```

**Comment by brechmos-stsci** [comment]
@nmearl could you please re-check what you are getting?  I would like to create a PR if you can confirm this is a bug.

**Comment by nmearl** [comment]
I cannot reproduce this either on master, or my own branches; either using astropy 3.0.3 or 3.0.4.

**Comment by brechmos-stsci** [comment]
@eteq (or anyone else) Could you try @nmearl's test code 4 comments above? 
```
from specutils import Spectrum1D; import numpy as np; import astropy.units as u
spec = Spectrum1D(spectral_axis=np.arange(20, 71) * u.Hz, flux=np.random.sample(30))
spec.wcs.world_to_pixel([31.7] * u.Hz)
```
 (I created a brand new conda environment, did `conda install astropy` and `pip install git+https://github.com/astropy/specutils.git`. These resulted in specutils 0.3.1.dev956 and astropy 3.0.4. I still get the error, which @nmearl  is not seeing, so am confused where things might be wrong.)

I want to see if someone else can reproduce this error or not.

**Comment by keflavich** [comment]
Well, the test code is no longer correct:
``` python
>>> spec = Spectrum1D(spectral_axis=np.arange(20, 71) * u.Hz,  flux=np.random.sample(30))
Traceback (most recent call last):
  File "<ipython-input-8-ffcfdf520921>", line 1, in <module>
    spec = Spectrum1D(spectral_axis=np.arange(20, 71) * u.Hz,  flux=np.random.sample(30))
TypeError: __init__() missing 1 required positional argument: 'wcs'
```

**Comment by keflavich** [comment]
I can reproduce the error. 
``` python
In [3]: from specutils import Spectrum1D; import numpy as np; import astropy.units as u

In [4]: spec = Spectrum1D(spectral_axis=np.arange(20, 71) * u.Hz,  flux=np.random.sample(30))
WARNING:root:GWCS does not store rest frequency information. Please define the rest value explicitly in the `Spectrum1D` object.
WARNING:root:GWCS does not store rest wavelength information. Please define the rest value explicitly in the `Spectrum1D` object.

In [5]: spec.wcs.world_to_pixel([31.7] * u.Hz)
Traceback (most recent call last):
  File "<ipython-input-5-cf8cd999aebc>", line 1, in <module>
    spec.wcs.world_to_pixel([31.7] * u.Hz)
  File "/Users/adam/repos/specutils/specutils/wcs/adapters/gwcs_adapter.py", line 79, in world_to_pixel
    return u.Quantity(self.wcs.invert(world_array),
  File "/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/gwcs-0.9.1-py3.6.egg/gwcs/wcs.py", line 293, in invert
    result = self.backward_transform(*args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/astropy/modeling/core.py", line 382, in __call__
    ('equivalencies', None)])
  File "/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/astropy/modeling/core.py", line 363, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
  File "/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/astropy/modeling/core.py", line 779, in __call__
    axis_ind = np.logical_or(inp < bbox[ind][0], inp > bbox[ind][1], out=axis_ind)
  File "/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/astropy/units/quantity.py", line 620, in __array_ufunc__
    converters, unit = converters_and_unit(function, method, *inputs)
  File "/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/astropy/units/quantity_helper.py", line 567, in converters_and_unit
    .format(function.__name__))
UnitsError: Can only apply 'less' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)


In [6]: import astropy

In [7]: astropy.__version__
Out[7]: '3.0.4'
```

**Comment by brechmos-stsci** [comment]
Is it as simple as converting to the correct units, then inverting?

This appears to work...
```
    def world_to_pixel(self, world_array):
        """
        Method for performing the world to pixel transformations.
        """

        # If a quantity, convert to the right unit, then strip the unit.
        if isinstance(world_array[0], u.Quantity):
            world_array = [element.to(self._wcs_unit).value for element in world_array]

        return u.Quantity([self.wcs.invert(x) for x in world_array], self._wcs_unit).to(
            self._unit, equivalencies=u.spectral()).value
```

**Comment by krittisharma** [comment]
This exact same error exists in the recent release of astropy. Could someone fix it please?
