### ISSUE TITLE
FITSWCSAdapter doesn't work with correlated celestial axes

### ISSUE THREAD

**Issue by astrofrog** [astropy/specutils#369]
The ``FITSWCSAdapter`` code includes:

```python
        self.axes = WCSAxes(
            longitude=self.wcs.sub([WCSSUB_LONGITUDE]),
            latitude=self.wcs.sub([WCSSUB_LATITUDE]),
            cubeface=self.wcs.sub([WCSSUB_CUBEFACE]),
            spectral=self.wcs.sub([WCSSUB_SPECTRAL]),
            stokes=self.wcs.sub([WCSSUB_STOKES]),
            celestial=self.wcs.sub([WCSSUB_CELESTIAL])
        )
```

However, ``self.wcs.sub([WCSSUB_LONGITUDE])`` fails if the WCS actually has celestial axes with e.g. a ``TAN`` projection:

```
0
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    spec = glue_data_to_spectrum1d(data, data.id['PRIMARY'])
  File "/Users/tom/Projects/Glue/STScI/specviz/specviz/third_party/glue/utils.py", line 72, in glue_data_to_spectrum1d
    spec1d = Spectrum1D(values, wcs=data.coords.wcs)
  File "/Users/tom/Dropbox/Code/Astropy/specutils/specutils/spectra/spectrum1d.py", line 79, in __init__
    wcs = WCSWrapper(wcs)
  File "/Users/tom/Dropbox/Code/Astropy/specutils/specutils/wcs/wcs_wrapper.py", line 41, in __new__
    return adapter_class(wcs, *args, **kwargs)
  File "/Users/tom/Dropbox/Code/Astropy/specutils/specutils/wcs/adapters/fitswcs_adapter.py", line 27, in __init__
    longitude=self.wcs.sub([WCSSUB_LONGITUDE]),
  File "/Users/tom/miniconda3/envs/dev/lib/python3.7/site-packages/astropy/wcs/wcs.py", line 559, in sub
    copy.wcs = self.wcs.sub(axes)
astropy.wcs._wcs.InconsistentAxisTypesError: ERROR 4 in wcs_types() at line 2522 of file cextern/wcslib/C/wcs.c:
Unmatched celestial axes.
```

**Comment by nmearl** [comment]
We no longer use the adapter approach, instead favoring the APE14 generic api usage. Closing.
