### ISSUE TITLE
Cannot complie current specutils master in new conda environment

### ISSUE THREAD

**Issue by hamogu** [astropy/specutils#464]
I'm failing to run the tests on a recent (yesterday) checkout of the specutils master. I'm installing python 3.7, astropy, and scipy through conda and then specutils with `python setup.py`. That stops for missing gwcs, so I pip install the last released gwcs version, but installing specutils fails with `ValueError: Don't know how to write out ASDF version 1.3.0`. Full output of the session is below:
```
[Hanss-MacBook-Air:~/code/specutils] hamogu% conda create -n specutils python scipy astropy ipython
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/hamogu/anaconda/envs/specutils

  added / updated specs:
    - astropy
    - ipython
    - python
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    appnope-0.1.0              |           py37_0           8 KB
    backcall-0.1.0             |           py37_0          20 KB
    decorator-4.4.0            |           py37_1          18 KB
    ipython-7.4.0              |   py37h39e3cac_0         1.1 MB
    ipython_genutils-0.2.0     |           py37_0          39 KB
    jedi-0.13.3                |           py37_0         236 KB
    more-itertools-7.0.0       |           py37_0          93 KB
    numpy-1.16.3               |   py37hacdab7b_0          49 KB
    numpy-base-1.16.3          |   py37h6575580_0         4.2 MB
    pexpect-4.7.0              |           py37_0          82 KB
    pickleshare-0.7.5          |           py37_0          12 KB
    prompt_toolkit-2.0.9       |           py37_0         488 KB
    ptyprocess-0.6.0           |           py37_0          23 KB
    pygments-2.3.1             |           py37_0         1.3 MB
    pytest-4.4.1               |           py37_0         355 KB
    scipy-1.2.1                |   py37h1410ff5_0        15.6 MB
    traitlets-4.3.2            |           py37_0         133 KB
    wcwidth-0.1.7              |           py37_0          23 KB
    ------------------------------------------------------------
                                           Total:        23.8 MB

The following NEW packages will be INSTALLED:

  appnope            pkgs/main/osx-64::appnope-0.1.0-py37_0
  astropy            pkgs/main/osx-64::astropy-3.1.2-py37h1de35cc_0
  atomicwrites       pkgs/main/osx-64::atomicwrites-1.3.0-py37_1
  attrs              pkgs/main/osx-64::attrs-19.1.0-py37_1
  backcall           pkgs/main/osx-64::backcall-0.1.0-py37_0
  blas               pkgs/main/osx-64::blas-1.0-mkl
  ca-certificates    pkgs/main/osx-64::ca-certificates-2019.1.23-0
  certifi            pkgs/main/osx-64::certifi-2019.3.9-py37_0
  decorator          pkgs/main/osx-64::decorator-4.4.0-py37_1
  intel-openmp       pkgs/main/osx-64::intel-openmp-2019.3-199
  ipython            pkgs/main/osx-64::ipython-7.4.0-py37h39e3cac_0
  ipython_genutils   pkgs/main/osx-64::ipython_genutils-0.2.0-py37_0
  jedi               pkgs/main/osx-64::jedi-0.13.3-py37_0
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  libgfortran        pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  mkl                pkgs/main/osx-64::mkl-2019.3-199
  mkl_fft            pkgs/main/osx-64::mkl_fft-1.0.10-py37h5e564d8_0
  mkl_random         pkgs/main/osx-64::mkl_random-1.0.2-py37h27c97d8_0
  more-itertools     pkgs/main/osx-64::more-itertools-7.0.0-py37_0
  ncurses            pkgs/main/osx-64::ncurses-6.1-h0a44026_1
  numpy              pkgs/main/osx-64::numpy-1.16.3-py37hacdab7b_0
  numpy-base         pkgs/main/osx-64::numpy-base-1.16.3-py37h6575580_0
  openssl            pkgs/main/osx-64::openssl-1.1.1b-h1de35cc_1
  parso              pkgs/main/noarch::parso-0.4.0-py_0
  pexpect            pkgs/main/osx-64::pexpect-4.7.0-py37_0
  pickleshare        pkgs/main/osx-64::pickleshare-0.7.5-py37_0
  pip                pkgs/main/osx-64::pip-19.0.3-py37_0
  pluggy             pkgs/main/osx-64::pluggy-0.9.0-py37_0
  prompt_toolkit     pkgs/main/osx-64::prompt_toolkit-2.0.9-py37_0
  psutil             pkgs/main/osx-64::psutil-5.6.1-py37h1de35cc_0
  ptyprocess         pkgs/main/osx-64::ptyprocess-0.6.0-py37_0
  py                 pkgs/main/osx-64::py-1.8.0-py37_0
  pygments           pkgs/main/osx-64::pygments-2.3.1-py37_0
  pytest             pkgs/main/osx-64::pytest-4.4.1-py37_0
  pytest-arraydiff   pkgs/main/osx-64::pytest-arraydiff-0.3-py37h39e3cac_0
  pytest-astropy     pkgs/main/osx-64::pytest-astropy-0.5.0-py37_0
  pytest-doctestplus pkgs/main/osx-64::pytest-doctestplus-0.3.0-py37_0
  pytest-openfiles   pkgs/main/osx-64::pytest-openfiles-0.3.2-py37_0
  pytest-remotedata  pkgs/main/osx-64::pytest-remotedata-0.3.1-py37_0
  python             pkgs/main/osx-64::python-3.7.3-h359304d_0
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  scipy              pkgs/main/osx-64::scipy-1.2.1-py37h1410ff5_0
  setuptools         pkgs/main/osx-64::setuptools-41.0.0-py37_0
  six                pkgs/main/osx-64::six-1.12.0-py37_0
  sqlite             pkgs/main/osx-64::sqlite-3.28.0-ha441bb4_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  traitlets          pkgs/main/osx-64::traitlets-4.3.2-py37_0
  wcwidth            pkgs/main/osx-64::wcwidth-0.1.7-py37_0
  wheel              pkgs/main/osx-64::wheel-0.33.1-py37_0
  xz                 pkgs/main/osx-64::xz-5.2.4-h1de35cc_4
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Proceed ([y]/n)? 


Downloading and Extracting Packages
scipy-1.2.1          | 15.6 MB   | ########################################################################################################### | 100% 
ipython-7.4.0        | 1.1 MB    | ########################################################################################################### | 100% 
decorator-4.4.0      | 18 KB     | ########################################################################################################### | 100% 
wcwidth-0.1.7        | 23 KB     | ########################################################################################################### | 100% 
pickleshare-0.7.5    | 12 KB     | ########################################################################################################### | 100% 
pexpect-4.7.0        | 82 KB     | ########################################################################################################### | 100% 
jedi-0.13.3          | 236 KB    | ########################################################################################################### | 100% 
pygments-2.3.1       | 1.3 MB    | ########################################################################################################### | 100% 
numpy-1.16.3         | 49 KB     | ########################################################################################################### | 100% 
ptyprocess-0.6.0     | 23 KB     | ########################################################################################################### | 100% 
appnope-0.1.0        | 8 KB      | ########################################################################################################### | 100% 
more-itertools-7.0.0 | 93 KB     | ########################################################################################################### | 100% 
traitlets-4.3.2      | 133 KB    | ########################################################################################################### | 100% 
numpy-base-1.16.3    | 4.2 MB    | ########################################################################################################### | 100% 
backcall-0.1.0       | 20 KB     | ########################################################################################################### | 100% 
ipython_genutils-0.2 | 39 KB     | ########################################################################################################### | 100% 
pytest-4.4.1         | 355 KB    | ########################################################################################################### | 100% 
prompt_toolkit-2.0.9 | 488 KB    | ########################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > conda activate specutils
#
# To deactivate an active environment, use:
# > conda deactivate
#

[Hanss-MacBook-Air:~/code/specutils] hamogu% conda_activate specutils
basename: illegal option -- t
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
Your Python environment has been changed to the 'specutils' conda environment. Here's the active version of Python:
/Users/hamogu/anaconda/envs/specutils/bin/python
Python 3.7.3
To switch back to your default Python environment, type 'source deactivate.csh'
(specutils)~/code/specutils% python setup.py test
running test
Searching for gwcs
Reading https://pypi.org/simple/gwcs/
Downloading https://files.pythonhosted.org/packages/15/16/022cd5349f5f0987b5b62bd031b7b1b59559fcee20e79631841d4f1c7f3c/gwcs-0.10.0.tar.gz#sha256=976bfbe52c1eb895f48d4c2beeee196a216edb34bd0a9da480caee7dff591ed3
Best match: gwcs 0.10.0
Processing gwcs-0.10.0.tar.gz
Writing /var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/easy_install-bey7wauy/gwcs-0.10.0/setup.cfg
Running gwcs-0.10.0/setup.py -q bdist_egg --dist-dir /var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/easy_install-bey7wauy/gwcs-0.10.0/egg-dist-tmp-giiduj2n
creating /Users/hamogu/code/specutils/.eggs/gwcs-0.10.0-py3.7.egg
Extracting gwcs-0.10.0-py3.7.egg to /Users/hamogu/code/specutils/.eggs

Installed /Users/hamogu/code/specutils/.eggs/gwcs-0.10.0-py3.7.egg
Searching for asdf
Reading https://pypi.org/simple/asdf/
Downloading https://files.pythonhosted.org/packages/fb/20/f2277af8f18587fa5b5d1319765d9fe5c67e778c29e206478ce68c4bc1d0/asdf-2.3.3.tar.gz#sha256=d02e936a83abd206e7bc65050d94e8848da648344dbec9e49dddc2bdc3bd6870
Best match: asdf 2.3.3
Processing asdf-2.3.3.tar.gz
Writing /var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/easy_install-vkpuj9ha/asdf-2.3.3/setup.cfg
Running asdf-2.3.3/setup.py -q bdist_egg --dist-dir /var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/easy_install-vkpuj9ha/asdf-2.3.3/egg-dist-tmp-f3onhghb
package init file 'asdf-standard/schemas/__init__.py' not found (or not a regular file)
package init file 'asdf-standard/reference_files/__init__.py' not found (or not a regular file)
creating /Users/hamogu/code/specutils/.eggs/asdf-2.3.3-py3.7.egg
Extracting asdf-2.3.3-py3.7.egg to /Users/hamogu/code/specutils/.eggs

Installed /Users/hamogu/code/specutils/.eggs/asdf-2.3.3-py3.7.egg
Searching for jsonschema<=2.6,>=2.3
Reading https://pypi.org/simple/jsonschema/
Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl#sha256=000e68abd33c972a5248544925a0cae7d1125f9bf6c58280d37546b946769a08
Best match: jsonschema 2.6.0
Processing jsonschema-2.6.0-py2.py3-none-any.whl
Installing jsonschema-2.6.0-py2.py3-none-any.whl to /Users/hamogu/code/specutils/.eggs
writing requirements to /Users/hamogu/code/specutils/.eggs/jsonschema-2.6.0-py3.7.egg/EGG-INFO/requires.txt

Installed /Users/hamogu/code/specutils/.eggs/jsonschema-2.6.0-py3.7.egg
Searching for pyyaml>=3.10
Reading https://pypi.org/simple/pyyaml/
Downloading https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz#sha256=436bc774ecf7c103814098159fbb84c2715d25980175292c648f2da143909f95
Best match: PyYAML 5.1
Processing PyYAML-5.1.tar.gz
Writing /var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/easy_install-3nmk0j36/PyYAML-5.1/setup.cfg
Running PyYAML-5.1/setup.py -q bdist_egg --dist-dir /var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/easy_install-3nmk0j36/PyYAML-5.1/egg-dist-tmp-ih3xzvjv
In file included from ext/_yaml.c:591:
ext/_yaml.h:2:10: fatal error: 'yaml.h' file not found
#include <yaml.h>
         ^~~~~~~~
1 error generated.
Error compiling module, falling back to pure Python
zip_safe flag not set; analyzing archive contents...
Copying PyYAML-5.1-py3.7-macosx-10.7-x86_64.egg to /Users/hamogu/code/specutils/.eggs

Installed /Users/hamogu/code/specutils/.eggs/PyYAML-5.1-py3.7-macosx-10.7-x86_64.egg
Searching for semantic_version>=2.3.1
Reading https://pypi.org/simple/semantic_version/
Downloading https://files.pythonhosted.org/packages/28/be/3a7241d731ba89063780279a5433f5971c1cf41735b64a9f874b7c3ff995/semantic_version-2.6.0-py3-none-any.whl#sha256=2d06ab7372034bcb8b54f2205370f4aa0643c133b7e6dbd129c5200b83ab394b
Best match: semantic-version 2.6.0
Processing semantic_version-2.6.0-py3-none-any.whl
Installing semantic_version-2.6.0-py3-none-any.whl to /Users/hamogu/code/specutils/.eggs

Installed /Users/hamogu/code/specutils/.eggs/semantic_version-2.6.0-py3.7.egg
installing to temporary directory: /private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-1xnffycc
warning: no files found matching 'ez_setup.py'
warning: no files found matching '*.pyx' under directory 'specutils'
warning: no files found matching '*.pxd' under directory 'specutils'
warning: no files found matching '*' under directory 'licenses'
warning: no files found matching '*' under directory 'cextern'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
warning: no files found matching 'astropy_helpers/ez_setup.py'
warning: no files found matching '*.pyx' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.h' under directory 'astropy_helpers/astropy_helpers'
no previously-included directories found matching 'astropy_helpers/build'
warning: no previously-included files matching '*.o' found anywhere in distribution
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-1xnffycc/lib/python3.7/site-packages/specutils/__init__.py", line 29, in <module>
    from .spectra import *
  File "/private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-1xnffycc/lib/python3.7/site-packages/specutils/spectra/__init__.py", line 5, in <module>
    from .spectrum1d import *  # noqa
  File "/private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-1xnffycc/lib/python3.7/site-packages/specutils/spectra/spectrum1d.py", line 8, in <module>
    from ..wcs import WCSWrapper, WCSAdapter
  File "/private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-1xnffycc/lib/python3.7/site-packages/specutils/wcs/__init__.py", line 1, in <module>
    from .wcs_wrapper import WCSWrapper
  File "/private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-1xnffycc/lib/python3.7/site-packages/specutils/wcs/wcs_wrapper.py", line 1, in <module>
    import gwcs
ModuleNotFoundError: No module named 'gwcs'
(specutils)~/code/specutils% pip install gwcs
Collecting gwcs
  Using cached https://files.pythonhosted.org/packages/15/16/022cd5349f5f0987b5b62bd031b7b1b59559fcee20e79631841d4f1c7f3c/gwcs-0.10.0.tar.gz
Requirement already satisfied: astropy in /Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages (from gwcs) (3.1.2)
Collecting asdf (from gwcs)
  Using cached https://files.pythonhosted.org/packages/fb/20/f2277af8f18587fa5b5d1319765d9fe5c67e778c29e206478ce68c4bc1d0/asdf-2.3.3.tar.gz
Requirement already satisfied: numpy>=1.13.0 in /Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages (from astropy->gwcs) (1.16.3)
Collecting semantic_version>=2.3.1 (from asdf->gwcs)
  Using cached https://files.pythonhosted.org/packages/28/be/3a7241d731ba89063780279a5433f5971c1cf41735b64a9f874b7c3ff995/semantic_version-2.6.0-py3-none-any.whl
Collecting pyyaml>=3.10 (from asdf->gwcs)
  Using cached https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz
Collecting jsonschema<=2.6,>=2.3 (from asdf->gwcs)
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages (from asdf->gwcs) (1.12.0)
Building wheels for collected packages: gwcs, asdf, pyyaml
  Building wheel for gwcs (setup.py) ... done
  Stored in directory: /Users/hamogu/Library/Caches/pip/wheels/70/c3/6f/f976c7390a4f73d34830cd0bd41d707e4118da6664aaef6a61
  Building wheel for asdf (setup.py) ... done
  Stored in directory: /Users/hamogu/Library/Caches/pip/wheels/1d/20/c6/2823bd2cdbf8b4e53bc583e5d3bd1dc316dc2a09c3d5625bda
  Building wheel for pyyaml (setup.py) ... done
  Stored in directory: /Users/hamogu/Library/Caches/pip/wheels/ad/56/bc/1522f864feb2a358ea6f1a92b4798d69ac783a28e80567a18b
Successfully built gwcs asdf pyyaml
Installing collected packages: semantic-version, pyyaml, jsonschema, asdf, gwcs
Successfully installed asdf-2.3.3 gwcs-0.10.0 jsonschema-2.6.0 pyyaml-5.1 semantic-version-2.6.0
(specutils)~/code/specutils% python setup.py test
running test
installing to temporary directory: /private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-zfzkg7nr
warning: no files found matching 'ez_setup.py'
warning: no files found matching '*.pyx' under directory 'specutils'
warning: no files found matching '*.pxd' under directory 'specutils'
warning: no files found matching '*' under directory 'licenses'
warning: no files found matching '*' under directory 'cextern'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
warning: no files found matching 'astropy_helpers/ez_setup.py'
warning: no files found matching '*.pyx' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.h' under directory 'astropy_helpers/astropy_helpers'
no previously-included directories found matching 'astropy_helpers/build'
warning: no previously-included files matching '*.o' found anywhere in distribution
Traceback (most recent call last):
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 435, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-zfzkg7nr/lib/python3.7/site-packages/specutils/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/versioning.py", line 52, in get_version_map
    with generic_io.get_file(version_map_path, 'r') as fd:
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/generic_io.py", line 1198, in get_file
    fd = open(realpath, realmode)
FileNotFoundError: [Errno 2] No such file or directory: '/.eggs/asdf-2.3.3-py3.7.egg/asdf/schemas/stsci.edu/asdf/version_map-1.3.0.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/type_index.py", line 57, in __init__
    version_map = get_version_map(self._version)
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/versioning.py", line 57, in get_version_map
    "Could not load version map for version {0}".format(version))
ValueError: Could not load version map for version 1.3.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/astropy/utils/decorators.py", line 860, in test
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/astropy/tests/runner.py", line 260, in test
    return runner.run_tests(**kwargs)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/astropy/tests/runner.py", line 605, in run_tests
    return super().run_tests(**kwargs)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/astropy/tests/runner.py", line 242, in run_tests
    return pytest.main(args=args, plugins=plugins)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 201, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 679, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 896, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 851, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 742, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 378, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 384, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 419, in _getconftestmodules
    mod = self._importconftest(conftestpath.realpath())
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 469, in _importconftest
    self.consider_conftest(mod)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 519, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 323, in register
    self.consider_module(plugin)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 525, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 530, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/config/__init__.py", line 557, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/hamogu/anaconda/envs/specutils/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 299, in load_module
    six.exec_(co, mod.__dict__)
  File "/private/var/folders/ml/hv25mzgx3k3bqzr21krjs5bw0000gn/T/specutils-test-zfzkg7nr/lib/python3.7/site-packages/.eggs/asdf-2.3.3-py3.7.egg/asdf/tests/schema_tester.py", line 23, in <module>
    _ctx = AsdfFile()
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/asdf.py", line 137, in __init__
    self.tree = {}
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/asdf.py", line 395, in tree
    self._validate(asdf_object, custom=bool(tree))
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/asdf.py", line 416, in _validate
    tree, self)
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/yamlutil.py", line 229, in walker
    tag = ctx.type_index.from_custom_type(type(node), ctx.version_string)
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/type_index.py", line 255, in from_custom_type
    write_type_index = _AsdfWriteTypeIndex(version, self)
  File ".eggs/asdf-2.3.3-py3.7.egg/asdf/type_index.py", line 63, in __init__
    self._version))
ValueError: Don't know how to write out ASDF version 1.3.0
```

**Comment by nmearl** [comment]
Curious. Can you try the following commands instead in your specutils directory

```bash
$ pip install -e .
$ pytest specutils
```

**Comment by hamogu** [comment]
Will try tonight. (It's on my laptop and that's at home.)

**Comment by hamogu** [comment]
Curiously the same setup for a fresh conda environment that failed for my mac (see above) works on my CentOS machine.

**Comment by hamogu** [comment]
`pip install -e .` etc. works. Mmm. So, I remembered `git clean` and now `python setup.py test` also works. So, it must have been some old stuff that was sitting around in my tree. I've not seen it before that that made `python setup.py install` fail, in particular with such a seemingly unrelated error message, but there is no use in investigating this further; solved! Thanks for your advice @nmearl which brought me on the right track.
