### ISSUE TITLE
A error in importing specutils

### ISSUE THREAD

**Issue by xuemuyu2010** [astropy/specutils#469]
Hi,
    I am trying to read fits "multispec" format. And as advised in some web. I want to use the comman "from specutils.io import read_fits". But there is mistake happened as follow. It seems that there is no module 'astropy.wcs.wcsapi'. But I have import astropy before import specutils. Is there something I have missed? Thanks for kindly help!

*******
Astro-Yu:python3.5 astro$ python3
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> from specutils.io import read_fits
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/__init__.py", line 29, in <module>
    from .spectra import *
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/spectra/__init__.py", line 5, in <module>
    from .spectrum1d import *  # noqa
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/spectra/spectrum1d.py", line 8, in <module>
    from ..wcs import WCSWrapper, WCSAdapter
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/wcs/__init__.py", line 1, in <module>
    from .wcs_wrapper import WCSWrapper
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/wcs/wcs_wrapper.py", line 1, in <module>
    import gwcs
  File "/Users/astro/anaconda/lib/python3.6/site-packages/gwcs/__init__.py", line 22, in <module>
    from .wcs import *   # noqa
  File "/Users/astro/anaconda/lib/python3.6/site-packages/gwcs/wcs.py", line 8, in <module>
    from .api import GWCSAPIMixin
  File "/Users/astro/anaconda/lib/python3.6/site-packages/gwcs/api.py", line 7, in <module>
    from astropy.wcs.wcsapi import BaseHighLevelWCS, BaseLowLevelWCS
ModuleNotFoundError: No module named 'astropy.wcs.wcsapi'
*******

**Comment by nmearl** [comment]
Can you give the versions of astropy and specutils you're using. At your terminal:

```bash
$ python -c "import astropy; print(astropy.__version__)"
$ python -c "import specutils; print(specutils.__version__)"
```

**Comment by xuemuyu2010** [comment]
> Can you give the versions of astropy and specutils you're using? At your terminal:
> 
> ```shell
> $ python -c "import astropy; print(astropy.__version__)"
> $ python -c "import specutils; print(specutils.__version__)"
> ```

Hi Earl,

The result is 
$ python -c "import astropy; print(astropy.__version__)" 
   1.0.4
$ python -c "import specutils; print(specutils.__version__)"
   Traceback (most recent call last):
      File "<string>", line 1, in <module>
   ImportError: No module named specutils


However, if I use the following command
$ python3 -c "import astropy; print(astropy.__version__)"

3.0.5

$ python3 -c "import specutils; print(specutils.__version__)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/__init__.py", line 29, in <module>
    from .spectra import *
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/spectra/__init__.py", line 5, in <module>
    from .spectrum1d import *  # noqa
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/spectra/spectrum1d.py", line 8, in <module>
    from ..wcs import WCSWrapper, WCSAdapter
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/wcs/__init__.py", line 1, in <module>
    from .wcs_wrapper import WCSWrapper
  File "/Users/astro/anaconda/lib/python3.6/site-packages/specutils/wcs/wcs_wrapper.py", line 1, in <module>
    import gwcs
  File "/Users/astro/anaconda/lib/python3.6/site-packages/gwcs/__init__.py", line 22, in <module>
    from .wcs import *   # noqa
  File "/Users/astro/anaconda/lib/python3.6/site-packages/gwcs/wcs.py", line 8, in <module>
    from .api import GWCSAPIMixin
  File "/Users/astro/anaconda/lib/python3.6/site-packages/gwcs/api.py", line 7, in <module>
    from astropy.wcs.wcsapi import BaseHighLevelWCS, BaseLowLevelWCS
ModuleNotFoundError: No module named 'astropy.wcs.wcsapi'



Thank you for your help.
Best,
YU

**Comment by nmearl** [comment]
@xuemuyu2010 The current astropy version is 3.1.2 -- could you try to update it to the latest? Also, be sure when doing `python -c "import specutils; print(specutils.__version__)"`, you use two underscores (`_`) before and after `version`. It should return a value; the current version is `0.5.2`.

**Comment by xuemuyu2010** [comment]
@nmearl Thank you very much. I works as you said. Thanks!!!

**Comment by nmearl** [comment]
Great! I'm going to close this issue, if you run into more problems, please feel free to open a new issue or re-open this one.
