### ISSUE TITLE
Spectrum1D.read fails on reading its own files written as 'tabular-fits' or 'wcs-fits'

### ISSUE THREAD

**Issue by dhomeier** [astropy/specutils#531]
Reading a `BINTABLE` spectrum written with
`spectrum.write('spectab.fits', format='tabular-fits')`
(after fixing the `TUNITn` issue, see #528) fails with a WCS error:
```
>>> spect = Spectrum1D.read('spectab.fits', format='tabular-fits')
WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.7/site-packages/astropy/nddata/mixins/ndio.py", line 54, in __call__
    return registry.read(self._cls, *args, **kwargs)
  File "/sw/lib/python3.7/site-packages/astropy/io/registry.py", line 523, in read
    data = reader(*args, **kwargs)
  File "/Users/derek/lib/python3.7/site-packages/specutils/io/default_loaders/tabular_fits.py", line 69, in tabular_fits_loader
    return generic_spectrum_from_table(tab, wcs=wcs, **kwargs)
  File "/Users/derek/lib/python3.7/site-packages/specutils/io/parsing_utils.py", line 208, in generic_spectrum_from_table
    meta=table.meta, wcs=wcs)
  File "/Users/derek/lib/python3.7/site-packages/specutils/spectra/spectrum1d.py", line 94, in __init__
    wcs = WCSWrapper(wcs)
  File "/Users/derek/lib/python3.7/site-packages/specutils/wcs/wcs_wrapper.py", line 41, in __new__
    return adapter_class(wcs, *args, **kwargs)
  File "/Users/derek/lib/python3.7/site-packages/specutils/wcs/adapters/fitswcs_adapter.py", line 47, in __init__
    self.axes = self.axes._replace(spectral=self.wcs.sub([self.spec_axis + 1]))
  File "/Users/derek/lib/python3.7/site-packages/specutils/wcs/adapters/fitswcs_adapter.py", line 92, in spec_axis
    "Cannot find a spectral axis in the provided WCS."
astropy.wcs._wcs.InvalidSubimageSpecificationError: Cannot find a spectral axis in the provided WCS.Are your 'ctype's correct?
```

_Originally posted by @dhomeier in https://github.com/astropy/specutils/pull/530#issuecomment-539088535_

**Comment by dhomeier** [comment]
The `wcs-fits` format fails - see https://github.com/astropy/specutils/pull/530#issuecomment-539016328 - with a
`ValueError: FITS fle input to wcs1d_fits_loader is not 1D`

**Comment by nmearl** [comment]
@dhomeier is this issue solved when you consider the fix for exporting the header object directly as from the `Spectrum1D` meta?

```python
tab = Table([disp, flux], names=("dispersion", "flux"), meta=meta.get('header'))
    if 'NAXIS' in tab.meta:
        tab.meta.remove('NAXIS')

    tab.write(file_name, format="fits", **kwargs)
```

**Comment by nmearl** [comment]
@dhomeier is this issue fixed by PR #539?

**Comment by dhomeier** [comment]
@nmearl no, that's what I left the ToDo comment at the end of `test_tabular_fits_writer` for.
However the errors apparently now have changed when adding these checks (current master and both Astropy 3.2.3 and 4.0rc2):
```
__________________________________________________________________________ test_tabular_fits_writer[wavelength] __________________________________________________________________________

tmpdir = local('/private/var/folders/7l/j6rbh6fw8xjc4w0059bv63_h00027w/T/pytest-of-derek/pytest-150/test_tabular_fits_writer_wavel0'), spectral_axis = 'wavelength'

    @pytest.mark.parametrize("spectral_axis",
                             ['wavelength', 'frequency', 'energy', 'wavenumber'])
    def test_tabular_fits_writer(tmpdir, spectral_axis):
        wlu = {'wavelength': u.AA, 'frequency': u.GHz, 'energy': u.eV,
               'wavenumber': u.cm**-1}
        # Create a small data set
        disp = np.arange(1,1.1,0.01)*wlu[spectral_axis]
        flux = np.ones(len(disp))*1.e-14*u.Jy
        unc = StdDevUncertainty(0.01*flux)
        spectrum = Spectrum1D(flux=flux, spectral_axis=disp, uncertainty=unc)
        tmpfile = str(tmpdir.join('_tst.fits'))
        spectrum.write(tmpfile, format='tabular-fits')
    
        # Read it in and check against the original
        table = Table.read(tmpfile, format='fits')
        assert table[spectral_axis].unit == spectrum.spectral_axis.unit
        assert table['flux'].unit == spectrum.flux.unit
        assert table['uncertainty'].unit == spectrum.uncertainty.unit
        assert quantity_allclose(table[spectral_axis], spectrum.spectral_axis)
        assert quantity_allclose(table['flux'], spectrum.flux)
        assert quantity_allclose(table['uncertainty'], spectrum.uncertainty.quantity)
    
        # Test spectrum with different flux unit
        flux = np.random.normal(0., 1.e-9, disp.shape[0]) * u.W * u.m**-2 * u.AA**-1
        unc = StdDevUncertainty(0.1 * np.sqrt(np.abs(flux.value)) * flux.unit)
        spectrum = Spectrum1D(flux=flux, spectral_axis=disp, uncertainty=unc)
    
        # Try to overwrite the file
        with pytest.raises(OSError, match=r'File exists:'):
            spectrum.write(tmpfile, format='tabular-fits')
        spectrum.write(tmpfile, format='tabular-fits', overwrite=True)
    
        table = Table.read(tmpfile)
        assert table['flux'].unit == spectrum.flux.unit
        assert quantity_allclose(table['flux'], spectrum.flux)
    
>       spectrum_1d = Spectrum1D.read(tmpfile, format='tabular-fits')

lib/python3.7/site-packages/specutils/tests/test_loaders.py:267: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/sw/lib/python3.7/site-packages/astropy/nddata/mixins/ndio.py:54: in __call__
    return registry.read(self._cls, *args, **kwargs)
/sw/lib/python3.7/site-packages/astropy/io/registry.py:523: in read
    data = reader(*args, **kwargs)
lib/python3.7/site-packages/specutils/io/default_loaders/tabular_fits.py:69: in tabular_fits_loader
    return generic_spectrum_from_table(tab, wcs=wcs, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

table = <Table length=11>
wavelength           flux               uncertainty      
 Angstrom     W / (Angstrom m2)      W / (...-06
      1.09   1.086098385320551e-10  1.042160441256792e-06
       1.1 -1.3889978221694653e-09 3.7269261089662957e-06
wcs = WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''  
CRVAL : 0.0  0.0  
CRPIX : 0.0  0.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 1.0  1.0  
NAXIS : 0  0
kwargs = {}, _find_spectral_axis_column = <function generic_spectrum_from_table.<locals>._find_spectral_axis_column at 0x120ee6a70>
_find_spectral_column = <function generic_spectrum_from_table.<locals>._find_spectral_column at 0x120ee6b90>, colnames = ['wavelength', 'flux', 'uncertainty']
spectral_axis_column = 'wavelength', spectral_axis = None, flux_column = None

    def generic_spectrum_from_table(table, wcs=None, **kwargs):
        """
        Load spectrum from an Astropy table into a Spectrum1D object.
        Uses the following logic to figure out which column is which:
    
         * Spectral axis (dispersion) is the first column with units
         compatible with u.spectral() or with length units such as 'pix'.
    
         * Flux is taken from the first column with units compatible with
         u.spectral_density(), or with other likely culprits such as
         'adu' or 'cts/s'.
    
         * Uncertainty comes from the next column with the same units as flux.
    
        Parameters
        ----------
        file_name: str
            The path to the ECSV file
        wcs : :class:`~astropy.wcs.WCS`
            A FITS WCS object. If this is present, the machinery will fall back
            to using the wcs to find the dispersion information.
    
        Returns
        -------
        data: Spectrum1D
            The spectrum that is represented by the data in this table.
    
        Raises
        ------
        Warns if uncertainty has zeros or negative numbers.
        Raises IOError if it can't figure out the columns.
    
        """
        # Local function to find the wavelength or frequency column
        def _find_spectral_axis_column(table,columns_to_search):
            """
            Figure out which column in a table holds the spectral axis (dispersion).
            Take the first column that has units compatible with u.spectral()
            equivalencies. If none meet that criterion, look for other likely
            length units such as 'pix'.
            """
            additional_valid_units = [u.Unit('pix')]
            found_column = None
    
            # First, search for a column with units compatible with Angstroms
            for c in columns_to_search:
                try:
                    table[c].to("AA",equivalencies=u.spectral())
                    found_column = c
                    break
                except:
                    continue
    
            # If no success there, check for other possible length units
            if found_column is None:
                for c in columns_to_search:
                    if table[c].unit in additional_valid_units:
                        found_column = c
                        break
    
            return found_column
    
        # Local function to find the flux column
        def _find_spectral_column(table,columns_to_search,spectral_axis):
            """
            Figure out which column in a table holds the fluxes or uncertainties.
            Take the first column that has units compatible with
            u.spectral_density() equivalencies. If none meet that criterion,
            look for other likely length units such as 'adu' or 'cts/s'.
            """
            additional_valid_units = [u.Unit('adu'),u.Unit('ct/s')]
            found_column = None
    
            # First, search for a column with units compatible with Janskies
            for c in columns_to_search:
                try:
                    table[c].to("Jy",equivalencies=u.spectral_density(spectral_axis))
                    found_column = c
                    break
                except:
                    continue
    
            # If no success there, check for other possible flux units
            if found_column is None:
                for c in columns_to_search:
                    if table[c].unit in additional_valid_units:
                        found_column = c
                        break
    
            return found_column
    
        # Make a copy of the column names so we can remove them as they are found
        colnames = table.colnames.copy()
    
        # Use the first column that has spectral unit as the dispersion axis
        spectral_axis_column = _find_spectral_axis_column(table, colnames)
    
        if spectral_axis_column is None and wcs is None:
            raise IOError("Could not identify column containing the wavelength, frequency or energy")
        elif wcs is not None:
            spectral_axis = None
        else:
            spectral_axis = table[spectral_axis_column].to(table[spectral_axis_column].unit)
            colnames.remove(spectral_axis_column)
    
        # Use the first column that has a spectral_density equivalence as the flux
        flux_column = _find_spectral_column(table,colnames,spectral_axis)
        if flux_column is None:
>           raise IOError("Could not identify column containing the flux")
E           OSError: Could not identify column containing the flux

lib/python3.7/site-packages/specutils/io/parsing_utils.py:185: OSError
```
or trying to read as `wcs1d-fits`:
```
__________________________________________________________________________ test_tabular_fits_writer[wavelength] __________________________________________________________________________

tmpdir = local('/private/var/folders/7l/j6rbh6fw8xjc4w0059bv63_h00027w/T/pytest-of-derek/pytest-153/test_tabular_fits_writer_wavel0'), spectral_axis = 'wavelength'

    @pytest.mark.parametrize("spectral_axis",
                             ['wavelength', 'frequency', 'energy', 'wavenumber'])
    def test_tabular_fits_writer(tmpdir, spectral_axis):
        wlu = {'wavelength': u.AA, 'frequency': u.GHz, 'energy': u.eV,
               'wavenumber': u.cm**-1}
        # Create a small data set
        disp = np.arange(1,1.1,0.01)*wlu[spectral_axis]
        flux = np.ones(len(disp))*1.e-14*u.Jy
        unc = StdDevUncertainty(0.01*flux)
        spectrum = Spectrum1D(flux=flux, spectral_axis=disp, uncertainty=unc)
        tmpfile = str(tmpdir.join('_tst.fits'))
        spectrum.write(tmpfile, format='tabular-fits')
    
        # Read it in and check against the original
        table = Table.read(tmpfile, format='fits')
        assert table[spectral_axis].unit == spectrum.spectral_axis.unit
        assert table['flux'].unit == spectrum.flux.unit
        assert table['uncertainty'].unit == spectrum.uncertainty.unit
        assert quantity_allclose(table[spectral_axis], spectrum.spectral_axis)
        assert quantity_allclose(table['flux'], spectrum.flux)
        assert quantity_allclose(table['uncertainty'], spectrum.uncertainty.quantity)
    
        # Test spectrum with different flux unit
        flux = np.random.normal(0., 1.e-9, disp.shape[0]) * u.W * u.m**-2 * u.AA**-1
        unc = StdDevUncertainty(0.1 * np.sqrt(np.abs(flux.value)) * flux.unit)
        spectrum = Spectrum1D(flux=flux, spectral_axis=disp, uncertainty=unc)
    
        # Try to overwrite the file
        with pytest.raises(OSError, match=r'File exists:'):
            spectrum.write(tmpfile, format='tabular-fits')
        spectrum.write(tmpfile, format='tabular-fits', overwrite=True)
    
        table = Table.read(tmpfile)
        assert table['flux'].unit == spectrum.flux.unit
        assert quantity_allclose(table['flux'], spectrum.flux)
    
>       spectrum_1d = Spectrum1D.read(tmpfile, format='wcs1d-fits')

lib/python3.7/site-packages/specutils/tests/test_loaders.py:267: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/sw/lib/python3.7/site-packages/astropy/nddata/mixins/ndio.py:54: in __call__
    return registry.read(self._cls, *args, **kwargs)
/sw/lib/python3.7/site-packages/astropy/io/registry.py:523: in read
    data = reader(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_name = '/private/var/folders/7l/j6rbh6fw8xjc4w0059bv63_h00027w/T/pytest-of-derek/pytest-153/test_tabular_fits_writer_wavel0/_tst.fits', spectral_axis_unit = None, flux_unit = None
hdu_idx = 0, kwargs = {}, hdulist = [<astropy.io.fits.hdu.image.PrimaryHDU object at 0x116333350>]
header = SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                    8 / arra... array dimensions                     
EXTEND  =                    T                                                  
wcs = WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''  
CRVAL : 0.0  0.0  
CRPIX : 0.0  0.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 1.0  1.0  
NAXIS : 0  0

    @data_loader("wcs1d-fits", identifier=identify_wcs1d_fits,
                 dtype=Spectrum1D, extensions=['fits'])
    def wcs1d_fits_loader(file_name, spectral_axis_unit=None, flux_unit=None,
                          hdu_idx=0, **kwargs):
        """
        Loader for single spectrum-per-HDU spectra in FITS files, with the spectral
        axis stored in the header as FITS-WCS.  The flux unit of the spectrum is
        determined by the 'BUNIT' keyword of the HDU (if present), while the
        spectral axis unit is set by the WCS's 'CUNIT'.
    
        Parameters
        ----------
        file_name : str
            The path to the FITS file.
        spectral_axis_unit: str or `~astropy.Unit`, optional
            Units of the spectral axis. If not given (or None), the unit will be
            inferred from the CUNIT in the WCS.  Not that if this is providded it
            will *override* any units the CUNIT provides.
        flux_unit: str or `~astropy.Unit`, optional
            Units of the flux for this spectrum. If not given (or None), the unit
            will be inferred from the BUNIT keyword in the header. Note that this
            unit will attempt to convert from BUNIT if BUNIT is present
        hdu_idx : int
            The index of the HDU to load into this spectrum.
    
        Notes
        -----
        Loader contributed by Kelle Cruz.
        """
        logging.info("Spectrum file looks like wcs1d-fits")
    
        with fits.open(file_name, **kwargs) as hdulist:
            header = hdulist[hdu_idx].header
            wcs = WCS(header)
    
            if wcs.naxis != 1:
>               raise ValueError('FITS fle input to wcs1d_fits_loader is not 1D')
E               ValueError: FITS fle input to wcs1d_fits_loader is not 1D

lib/python3.7/site-packages/specutils/io/default_loaders/wcs_fits.py:67: ValueError
```

**Comment by dhomeier** [comment]
I guess central to the problem is that the `tabular_fits` loader insists on constructing a `wcs` transformation that requires `CTYPE*` information, while those keys do not even exist in the `BINTABLE` header...
