### ISSUE TITLE
fit_generic_continuum and fit_continuum giving TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by Ramlalunni** [astropy/specutils#596]
Hi,

I have tried to run the example code in the specutils documentation from: https://specutils.readthedocs.io/en/stable/fitting.html#continuum-fitting

It gives a TypeError: 'int' object is not callable.
The full output is given below:
######

runfile('/home/lal/Ramlal/M.Sc. Project/TRIALS - PNG239.6+13.9/Flux Comparison/trial.py', wdir='/home/lal/Ramlal/M.Sc. Project/TRIALS - PNG239.6+13.9/Flux Comparison')
Traceback (most recent call last):

  File "/home/lal/Ramlal/M.Sc. Project/TRIALS - PNG239.6+13.9/Flux Comparison/trial.py", line 20, in <module>
    g1_fit = fit_generic_continuum(spectrum)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/continuum.py", line 57, in fit_generic_continuum
    return fit_continuum(spectrum_smoothed, model, fitter, exclude_regions, weights)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/continuum.py", line 97, in fit_continuum
    continuum_spectrum = fit_lines(spectrum, model, fitter, exclude_regions, weights)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 360, in fit_lines
    ignore_units, **kwargs)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 476, in _fit_lines
    _strip_units_from_model(model, spectrum, convert=not ignore_units)

  File "/home/lal/Software/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 604, in _strip_units_from_model
    compound_model = model_in.n_submodels() > 1

TypeError: 'int' object is not callable

######

Does anybody know why this is happening and how it can be solved? Please help out, i need this urgently.

Thanks.

**Comment by nmearl** [comment]
Hi @Ramlalunni. What version of astropy and specutils do you have installed?

**Comment by Ramlalunni** [comment]
Hi @nmearl,

Thanks for reaching out quickly. Please see the following.

#####
`import astropy, specutils`
`astropy.__version__`
Out[2]: '4.0'
`specutils.__version__`
Out[3]: '0.6'
#####

`conda update specutils` and `conda update astropy` give the output:

> All requested packages already installed.

I have Anaconda installed, and I am using Spyder 4.0.1 to run the codes with Python 3.7, in an Ubuntu 19.10 laptop.

Please let me know if you need any more details. I really need to get this working for my Master's thesis project.

Thanks.

**Comment by nmearl** [comment]
Please see the [response](https://github.com/astropy/specutils/issues/563#issuecomment-595272370) in #563.

**Comment by nmearl** [comment]
Since this is the same issue as #563, I'm going to close this one and we can continue the conversation over there.
