### ISSUE TITLE
Problem with fit_generic_continuum

### ISSUE THREAD

**Issue by B1GeasY** [astropy/specutils#668]
A type error happens when I want to fit a continuum:

runfile('/Users/k/Desktop/Woring space/untitled5.py', wdir='/Users/k/Desktop/Woring space')
Traceback (most recent call last):

  File "/Users/k/Desktop/Woring space/untitled5.py", line 58, in <module>
    conti = fit_generic_continuum(sp, exclude_regions = line_region)

  File "/Users/k/anaconda3/lib/python3.7/site-packages/specutils/fitting/continuum.py", line 57, in fit_generic_continuum
    return fit_continuum(spectrum_smoothed, model, fitter, exclude_regions, weights)

  File "/Users/k/anaconda3/lib/python3.7/site-packages/specutils/fitting/continuum.py", line 97, in fit_continuum
    continuum_spectrum = fit_lines(spectrum, model, fitter, exclude_regions, weights)

  File "/Users/k/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 360, in fit_lines
    ignore_units, **kwargs)

  File "/Users/k/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 476, in _fit_lines
    _strip_units_from_model(model, spectrum, convert=not ignore_units)

  File "/Users/k/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py", line 604, in _strip_units_from_model
    compound_model = model_in.n_submodels() > 1

TypeError: 'int' object is not callable

I checked my code but it still shows.

Could you please help me with this problem?

**Comment by nmearl** [comment]
Hi @B1GeasY can you provided your current specutils and astropy versions as well as the code snippet that's causing the error?

**Comment by B1GeasY** [comment]
> Hi @B1GeasY can you provided your current specutils and astropy versions as well as the code snippet that's causing the error?

My astropy is 4.0 and specutils is 0.6.

Here is my code, fl and wl are the flux and lambda from data fits file:
    sp = Spectrum1D(flux=fl*u.Jy,spectral_axis=wl*u.um)
    rest_spec = gaussian_smooth(sp, stddev=2)
    line_region = SpectralRegion(5.8*u.um,8*u.um)
    conti = fit_generic_continuum(sp, exclude_regions = line_region)

**Comment by nmearl** [comment]
Thanks! Can you update your specutils to the latest 1.0 release and see if you get the same error? This may be fixed in the latest version.

**Comment by B1GeasY** [comment]
> Thanks! Can you update your specutils to the latest 1.0 release and see if you get the same error? This may be fixed in the latest version.

Thank you for your advice! Updating works!

**Comment by nmearl** [comment]
Glad to hear! Feel free to open anymore issues if you run into problems.
